apiVersion: v1
kind: Service
metadata:
  name: interop-att-fiscalcode-verification
  namespace: {{NAMESPACE}}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: interop-att-fiscalcode-verification
