version: "3"
name: pagopa-interop
services:

  localstack:
    image: localstack/localstack
    container_name: localstack-test
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs,sns,lambda,dynamodb,apigateway,kms
      - DEBUG=1
    restart: unless-stopped
  postgres:
    image: postgres:14
    container_name: postgres-test
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    command: -c 'max_connections=512' -c 'wal_level=logical'

networks:
  develop-network:
    name: interop-att-eservice-network
    driver: bridge
