apiVersion: v1
kind: Service
metadata:
  name: interop-att-inad-verification
  namespace: {{NAMESPACE}}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: http
      targetPort: 3000
      protocol: TCP
    - port: 3443
      name: https
      targetPort: 3443
      protocol: TCP
  selector:
    app: interop-att-inad-verification
