CREATE TABLE "att"."addresses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"address_type" text,
	"note_address" text,
	"address_start_date" text,
	"presso" text,
	"address_municipality_name" text,
	"address_municipality_istat_code" text,
	"address_municipality_acronym_istat_province" text,
	"address_municipality_place_description" text,
	"toponym_cod_type" text,
	"toponym_type" text,
	"toponym_origin_type" text,
	"toponym_cod" text,
	"toponym_denomination" text,
	"toponym_source" text,
	"civic_cod" text,
	"civic_source" text,
	"civic_number" text,
	"metric" text,
	"prog_snc" text,
	"letter" text,
	"exponent1" text,
	"color" text,
	"internal_court" text,
	"internal_stairs" text,
	"internal1" text,
	"esp_internal1" text,
	"internal2" text,
	"esp_internal2" text,
	"external_stairs" text,
	"secondary" text,
	"floor" text,
	"nui" text,
	"isolated" text,
	"foreign_cap" text,
	"foreign_place_description" text,
	"foreign_country_description" text,
	"foreign_country_state" text,
	"foreign_province_county" text,
	"foreign_toponym_denomination" text,
	"foreign_toponym_civic_number" text,
	"consulate_cod" text,
	"consulate_description" text
);
--> statement-breakpoint
CREATE TABLE "att"."subjects" (
	"uuid" uuid PRIMARY KEY NOT NULL,
	"id" text NOT NULL,
	"subject_id" text NOT NULL,
	"surname" text,
	"name" text,
	"gender" text,
	"birth_event_date" text,
	"birth_exceptional_place" text,
	"birth_municipality_name" text,
	"birth_municipality_istat_code" text,
	"birth_municipality_acronym_istat_province" text,
	"birth_municipality_place_description" text,
	"birth_place_description" text,
	"birth_country_description" text,
	"birth_cod_state" text,
	"birth_province_county" text,
	"address_id" uuid NOT NULL
);
--> statement-breakpoint
ALTER TABLE "att"."subjects" ADD CONSTRAINT "subjects_address_id_addresses_id_fk" FOREIGN KEY ("address_id") REFERENCES "att"."addresses"("id") ON DELETE no action ON UPDATE no action;