apiVersion: v1
kind: Service
metadata:
  name: interop-att-trial-service-api
  namespace: {{NAMESPACE}}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: http
      targetPort: 3000
      protocol: TCP
  selector:
    app: interop-att-trial-service-api
