apiVersion: v1
kind: ConfigMap
metadata:
  name: residence-verification-configmap
  namespace: att
data:
  SKIP_JWT_VERIFICATION: {{SKIP_JWT_VERIFICATION}}
  WELL_KNOWN_URLS: {{WELL_KNOWN_URLS}}
  TOKEN_ISS: {{TOKEN_ISS}}
  TOKEN_AUD: {{TOKEN_AUD}}
  TOKEN_TYP: {{TOKEN_TYP}}
  SKIP_INTEROPERABILITY_VERIFICATION: {{SKIP_INTEROPERABILITY_VERIFICATION}}
  TOKEN_INTEROPERABILITY_SUBJECT: {{TOKEN_INTEROPERABILITY_SUBJECT}}
  TOKEN_INTEROPERABILITY_AUDIENCE: {{TOKEN_INTEROPERABILITY_AUDIENCE}}
  TOKEN_INTEROPERABILITY_ISSUER: {{TOKEN_INTEROPERABILITY_ISSUER}}
  TOKEN_INTEROPERABILITY_EXPIRATION_SECONDS: {{TOKEN_INTEROPERABILITY_EXPIRATION_SECONDS}}
  TOKEN_INTEROPERABILITY_HOST: {{TOKEN_INTEROPERABILITY_HOST}}
  TOKEN_INTEROPERABILITY_KID: {{TOKEN_INTEROPERABILITY_KID}}
  TOKEN_FROM_ACCESS_CODE: {{TOKEN_FROM_ACCESS_CODE}}
  KMS_LOCAL_CONFIG: {{KMS_LOCAL_CONFIG}}
  AWS_CONFIG_FILE: {{AWS_CONFIG_FILE}}
  KMS_KEYID: {{KMS_KEYID}}
  KMS_MAX_ACQUISITION_TIMEOUT_SECONDS: {{KMS_MAX_ACQUISITION_TIMEOUT_SECONDS}}
  REDIS_ENDPOINT: {{REDIS_ENDPOINT}}

