apiVersion: apps/v1
kind: Deployment
metadata:
  name: interop-att-residence-verification
  namespace: {{NAMESPACE}}
  labels:
    app: interop-att-residence-verification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interop-att-residence-verification
  template:
    metadata:
      labels:
        app: interop-att-residence-verification
    spec:
      serviceAccountName: {{SERVICEACCOUNT}}
      containers:
        - name: interop-att-residence-verification
#          image: ghcr.io/pagopa/interop-att-residence-verification:{{RESIDENCEVERIFICATIONIMAGEDIGEST}}
          image: {{RESIDENCEVERIFICATIONIMAGE}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 1.0
              memory: 2Gi
            limits:
              cpu: 1.0
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /residence-verification/status
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /residence-verification/status
              port: http
            initialDelaySeconds: 15
            periodSeconds: 120
          env:
            - name: PORT
              value: "3000"
            - name: HOST
              value: "0.0.0.0"
            - name: LOG_LEVEL
              value: info
          envFrom:
            - configMapRef:
                name: residence-verification-configmap
